/* GLOBAL VARIABLES */
const h1 = document.querySelector("h1");
const gridSizeElem = document.querySelector(".grid-size");
const sketch = document.querySelector(".sketch");
const buttons = document.querySelectorAll(".button");
const resizeBtn = document.querySelector(".resizeBtn");
const clearBtn = document.querySelector(".clearBtn");
const colorPicker = document.querySelector(".color-picker");
const randomBtn = document.querySelector("#random");